name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install backend dependencies
        working-directory: backend
        run: npm install

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Run backend tests
        working-directory: backend
        run: npm test
      - name: Build backend Docker image
        run: docker build -t devops-backend ./backend
      - name: Build frontend Docker image
        run: docker build -t devops-frontend ./frontend
